
---
- name: Pull docker image of devopscalc
  hosts: all
  tasks:
    - name: Pull devopscalc devops image
      docker_image:
        name: satvi4/calc
        source: pull

    - name: Create & Start Calculator Docker Container
      docker_container:
        name: calc
        image: satvi4/calc
        state: started
        tty: yes
        interactive: yes