- name: Pull and run docker image
  hosts: localhost
  tasks:

    - name: pull docker image
      shell: docker pull satvi4/calc

    - name: run container
      shell: docker run -i -t --name calculator -d satvi4/calc
