- name: Pull and run docker image
  hosts: localhost
  tasks:

    - name: pull docker image
      shell: docker pull sam1234gupta/mini_project:latest

    - name: run container
      shell: docker run -i -t --name calculator -d sam1234gupta/mini_project
